### ISSUE TITLE
inference wrong

### ISSUE THREAD

**Issue by lianshushu** [antoine77340/Youtube-8M-WILLOW#16]
I get an error when running 

python inference.py --output_file=test-lstm-0002-val-150-random.csv --input_data_pattern="/data/dataset/yt8m/video-level/test/test*.tfrecord" --model=LstmModel --train_dir="/data/yt8m/public" --frame_features=True --feature_names="rgb,audio" --feature_sizes="1024,128" --batch_size=1024 --base_learning_rate=0.0002 --iterations=150 --lstm_random_sequence=True --run_once=True --top_k=50

Traceback (most recent call last):
  File "inference.py", line 206, in <module>
    app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "inference.py", line 202, in main
    FLAGS.output_file, FLAGS.batch_size, FLAGS.top_k)
  File "inference.py", line 175, in inference
    coord.join(threads)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1259, in _single_operation_run
    None)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Feature list 'audio' is required but could not be found.  Did you mean to include it in feature_list_dense_missing_assumed_empty or feature_list_dense_defaults?

**Comment by estathop** [comment]
you are probably trying to process video level features whereas his code I think is for frame level features, I don't know if it would work by changing --feature_names="rgb,audio" to --feature_names="mean_rgb,mean_audio" because that's what the features from video level are supposed to be.

**Comment by zhangatao** [comment]
Hello, I am experiencing the same problem as you now, do you solve it now

**Comment by zhangatao** [comment]
> I get an error when running
> 
> python inference.py --output_file=test-lstm-0002-val-150-random.csv --input_data_pattern="/data/dataset/yt8m/video-level/test/test*.tfrecord" --model=LstmModel --train_dir="/data/yt8m/public" --frame_features=True --feature_names="rgb,audio" --feature_sizes="1024,128" --batch_size=1024 --base_learning_rate=0.0002 --iterations=150 --lstm_random_sequence=True --run_once=True --top_k=50
> 
> Traceback (most recent call last):
> File "inference.py", line 206, in
> app.run()
> File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
> _sys.exit(main(argv))
> File "inference.py", line 202, in main
> FLAGS.output_file, FLAGS.batch_size, FLAGS.top_k)
> File "inference.py", line 175, in inference
> coord.join(threads)
> File "/usr/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
> six.reraise(*self._exc_info_to_raise)
> File "/usr/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
> enqueue_callable()
> File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1259, in _single_operation_run
> None)
> File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Feature list 'audio' is required but could not be found. Did you mean to include it in feature_list_dense_missing_assumed_empty or feature_list_dense_defaults?

Hello, I am experiencing the same problem as you now, do you solve it now
