### ISSUE TITLE
Alway crash down after hours

### ISSUE THREAD

**Issue by wincle** [antoine77340/Youtube-8M-WILLOW#2]
I have met a problem, when I training the model after hours, it will crash down, I could not find why did it happened, can you help me finger this. I'm using tensorflow 1.3.
Here is log:

INFO:tensorflow:/job:master/task:0: training step 88648| Hit@1: 0.91 PERR: 0.79 GAP: 0.84 Loss: 5.15765
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, truncated record at 72435675
     [[Node: train_input/ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](train_input/TFRecordReaderV2_1, train_input/input_producer)]]
     [[Node: train_input/SparseToDense_1/_407 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_33_train_input/SparseToDense_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
INFO:tensorflow:/job:master/task:0: training step 88649| Hit@1: 0.82 PERR: 0.67 GAP: 0.81 Loss: 5.31512
INFO:tensorflow:gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe/model.ckpt-88649 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:/job:master/task:0: Exporting the model at step 88649 to gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe/export/step_88649.
2017-08-26 07:09:39.978262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:02:00.0, compute capability: 3.5)
INFO:tensorflow:Restoring parameters from gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe/model.ckpt-88649
INFO:tensorflow:No assets to save.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe/export/step_88649/saved_model.pb
error:Tensor("map/while/Minimum:0", shape=(), dtype=int32) Tensor("map/while/Minimum_2:0", shape=(), dtype=int32)
Traceback (most recent call last):
  File "train.py", line 638, in <module>
    app.run()
  File "/data1/wangchao16/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 626, in main
    FLAGS.export_model_steps).run(start_new_model=FLAGS.start_new_model)
  File "train.py", line 428, in run
    task_as_string(self.task))
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/data1/wangchao16/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/data1/wangchao16/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/data1/wangchao16/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/data1/wangchao16/local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/data1/wangchao16/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1229, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/data1/wangchao16/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    c_api.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 72435675
     [[Node: train_input/ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](train_input/TFRecordReaderV2_1, train_input/input_producer)]]
     [[Node: train_input/SparseToDense_1/_407 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_33_train_input/SparseToDense_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by antoine77340** [comment]
Hi, I got the same error when I started to work on this project and many had the same problem.
This is because there is at least one of the training (or validation) tensorflow record file that is corrupted. You should re-download it.

**Comment by wincle** [comment]
Thx! It helps me a lot.
I have use these record file trained a model with  168,000 steps , It's a pity to discard the model , can I train this model continued with new fixed record file?

**Comment by antoine77340** [comment]
Yes I do not think there is any problem
